language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "2.7"

dist: trusty

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      name: "linting"
      env:
        - LINT_CHECK="1"

    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"
          EXCLUDE="partner_financial_risk_adjustment,partner_financial_risk_limit_change_request,partner_financial_risk_policy,partner_sale_risk_adjustment,partner_sale_risk_invoice_link,partner_sale_risk_limit_change_request,partner_sale_risk_policy,partner_single_sale_risk,partner_single_sale_risk_limit_change_request,partner_single_sale_risk_policy,partner_app_partner_risk,partner_app_partner_risk,partner_app_partner_risk_policy,partner_app_risk_adjustment,partner_app_risk_limit_change_request"
env:
  global:
    - VERSION="8.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    - WKHTMLTOPDF_VERSION="0.12.5"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
