language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MQT_TEST_DB="odoo_1" EXCLUDE="partner_app_partner_risk,partner_app_partner_risk_policy,partner_app_risk_adjustment,partner_app_risk_limit_change_request,partner_financial_risk_adjustment,partner_financial_risk_limit_change_request,partner_financial_risk_policy,partner_sale_risk_adjustment,partner_sale_risk_invoice_link,partner_sale_risk_limit_change_request,partner_sale_risk_policy,partner_single_sale_risk_limit_change_request,partner_single_sale_risk_policy,partner_single_sale_risk"
  - TESTS="1" ODOO_REPO="OCA/OCB" MQT_TEST_DB="ocb_1" EXCLUDE="partner_app_partner_risk,partner_app_partner_risk_policy,partner_app_risk_adjustment,partner_app_risk_limit_change_request,partner_financial_risk_adjustment,partner_financial_risk_limit_change_request,partner_financial_risk_policy,partner_sale_risk_adjustment,partner_sale_risk_invoice_link,partner_sale_risk_limit_change_request,partner_sale_risk_policy,partner_single_sale_risk_limit_change_request,partner_single_sale_risk_policy,partner_single_sale_risk"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="partner_single_sale_risk" MQT_TEMPLATE_DB="odoo_1" MQT_TEST_DB="odoo_2"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="partner_single_sale_risk" MQT_TEMPLATE_DB="ocb_1" MQT_TEST_DB="ocb_2"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="partner_financial_risk_policy,partner_sale_risk_policy,partner_single_sale_risk_policy" MQT_TEMPLATE_DB="odoo_2" MQT_TEST_DB="odoo_3"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="partner_financial_risk_policy,partner_sale_risk_policy,partner_single_sale_risk_policy" MQT_TEMPLATE_DB="ocb_2" MQT_TEST_DB="ocb_3"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="partner_financial_risk_adjustment,partner_sale_risk_adjustment" MQT_TEMPLATE_DB="odoo_2" MQT_TEST_DB="odoo_3"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="partner_financial_risk_adjustment,partner_sale_risk_adjustment" MQT_TEMPLATE_DB="ocb_2" MQT_TEST_DB="ocb_3"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="partner_financial_risk_limit_change_request,partner_sale_risk_limit_change_request,partner_single_sale_risk_limit_change_request" MQT_TEMPLATE_DB="odoo_2" MQT_TEST_DB="odoo_4"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="partner_financial_risk_limit_change_request,partner_sale_risk_limit_change_request,partner_single_sale_risk_limit_change_request" MQT_TEMPLATE_DB="ocb_2" MQT_TEST_DB="ocb_4"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/open-synergy/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - sed -i 's/manifest_required_author\=.*/manifest_required_author="OpenSynergy Indonesia"/g' ${HOME}/maintainer-quality-tools/travis/cfg/travis_run_pylint_pr.cfg
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
